// Code generated by go-swagger; DO NOT EDIT.

package course_grading_periods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams creates a new DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized.
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams() *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithTimeout creates a new DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithTimeout(timeout time.Duration) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{

		timeout: timeout,
	}
}

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithContext creates a new DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithContext(ctx context.Context) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{

		Context: ctx,
	}
}

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithHTTPClient creates a new DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithHTTPClient(client *http.Client) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{
		HTTPClient: client,
	}
}

/*DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams contains all the parameters to send to the API endpoint
for the delete learn API public v1 courses course ID gradebook periods period ID operation typically these are written to a http.Request
*/
type DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams struct {

	/*CourseID
	 The course or organization ID.  This may be the primary ID, or any of the secondary IDs prefixed with the ID type.

	| ID type    | Example                               |
	|------------|---------------------------------------|
	| primary    | _123_1                                |
	| externalId | externalId:math101                    |
	| courseId   | courseId:math101                      |
	| uuid       | uuid:915c7567d76d444abf1eed56aad3beb5 |


	*/
	CourseID string
	/*PeriodID*/
	PeriodID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithTimeout(timeout time.Duration) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithContext(ctx context.Context) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithHTTPClient(client *http.Client) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCourseID adds the courseID to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithCourseID(courseID string) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetCourseID(courseID string) {
	o.CourseID = courseID
}

// WithPeriodID adds the periodID to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithPeriodID(periodID string) *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetPeriodID(periodID)
	return o
}

// SetPeriodID adds the periodId to the delete learn API public v1 courses course ID gradebook periods period ID params
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetPeriodID(periodID string) {
	o.PeriodID = periodID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param courseId
	if err := r.SetPathParam("courseId", o.CourseID); err != nil {
		return err
	}

	// path param periodId
	if err := r.SetPathParam("periodId", o.PeriodID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
