// Code generated by go-swagger; DO NOT EDIT.

package course_grading_periods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams creates a new PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized.
func NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams() *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithTimeout creates a new PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithTimeout(timeout time.Duration) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{

		timeout: timeout,
	}
}

// NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithContext creates a new PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithContext(ctx context.Context) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{

		Context: ctx,
	}
}

// NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithHTTPClient creates a new PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParamsWithHTTPClient(client *http.Client) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams{
		HTTPClient: client,
	}
}

/*PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams contains all the parameters to send to the API endpoint
for the patch learn API public v1 courses course ID gradebook periods period ID operation typically these are written to a http.Request
*/
type PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams struct {

	/*Associate*/
	Associate *bool
	/*CourseID
	 The course or organization ID.  This may be the primary ID, or any of the secondary IDs prefixed with the ID type.

	| ID type    | Example                               |
	|------------|---------------------------------------|
	| primary    | _123_1                                |
	| externalId | externalId:math101                    |
	| courseId   | courseId:math101                      |
	| uuid       | uuid:915c7567d76d444abf1eed56aad3beb5 |


	*/
	CourseID string
	/*Fields
	  A comma-delimited list of fields to include in the response. If not specified, all fields will be returned.

	*/
	Fields *string
	/*Input*/
	Input PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDBody
	/*PeriodID*/
	PeriodID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithTimeout(timeout time.Duration) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithContext(ctx context.Context) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithHTTPClient(client *http.Client) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssociate adds the associate to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithAssociate(associate *bool) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetAssociate(associate)
	return o
}

// SetAssociate adds the associate to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetAssociate(associate *bool) {
	o.Associate = associate
}

// WithCourseID adds the courseID to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithCourseID(courseID string) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetCourseID(courseID string) {
	o.CourseID = courseID
}

// WithFields adds the fields to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithFields(fields *string) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithInput adds the input to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithInput(input PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDBody) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetInput(input PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDBody) {
	o.Input = input
}

// WithPeriodID adds the periodID to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WithPeriodID(periodID string) *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams {
	o.SetPeriodID(periodID)
	return o
}

// SetPeriodID adds the periodId to the patch learn API public v1 courses course ID gradebook periods period ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) SetPeriodID(periodID string) {
	o.PeriodID = periodID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchLearnAPIPublicV1CoursesCourseIDGradebookPeriodsPeriodIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Associate != nil {

		// query param associate
		var qrAssociate bool
		if o.Associate != nil {
			qrAssociate = *o.Associate
		}
		qAssociate := swag.FormatBool(qrAssociate)
		if qAssociate != "" {
			if err := r.SetQueryParam("associate", qAssociate); err != nil {
				return err
			}
		}

	}

	// path param courseId
	if err := r.SetPathParam("courseId", o.CourseID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if err := r.SetBodyParam(o.Input); err != nil {
		return err
	}

	// path param periodId
	if err := r.SetPathParam("periodId", o.PeriodID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
