// Code generated by go-swagger; DO NOT EDIT.

package institutional_hierarchy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesReader is a Reader for the GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCourses structure.
type GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK creates a GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK with default headers values
func NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK() *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK {
	return &GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK{}
}

/*GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK handles this case with default header values.

OK
*/
type GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK struct {
	Payload *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/institutionalHierarchy/nodes/{nodeId}/courses][%d] getLearnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesOK  %+v", 200, o.Payload)
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK) GetPayload() *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody {
	return o.Payload
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden creates a GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden with default headers values
func NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden() *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden {
	return &GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden{}
}

/*GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden handles this case with default header values.

Forbidden
*/
type GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/institutionalHierarchy/nodes/{nodeId}/courses][%d] getLearnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesForbidden  %+v", 403, o.Payload)
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound creates a GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound with default headers values
func NewGetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound() *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound {
	return &GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound{}
}

/*GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound handles this case with default header values.

Not Found
*/
type GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/institutionalHierarchy/nodes/{nodeId}/courses][%d] getLearnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesNotFound  %+v", 404, o.Payload)
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody get learn API public v1 institutional hierarchy nodes node ID courses o k body
swagger:model GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody
*/
type GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody struct {

	// paging
	Paging *models.PagingInfo `json:"paging,omitempty"`

	// results
	// Required: true
	Results []*models.HierarchyNodeCourse `json:"results"`
}

// Validate validates this get learn API public v1 institutional hierarchy nodes node ID courses o k body
func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePaging(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody) validatePaging(formats strfmt.Registry) error {

	if swag.IsZero(o.Paging) { // not required
		return nil
	}

	if o.Paging != nil {
		if err := o.Paging.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getLearnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesOK" + "." + "paging")
			}
			return err
		}
	}

	return nil
}

func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("getLearnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getLearnApiPublicV1InstitutionalHierarchyNodesNodeIdCoursesOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody) UnmarshalBinary(b []byte) error {
	var res GetLearnAPIPublicV1InstitutionalHierarchyNodesNodeIDCoursesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
