// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// GetLearnAPIPublicV1SystemRolesReader is a Reader for the GetLearnAPIPublicV1SystemRoles structure.
type GetLearnAPIPublicV1SystemRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLearnAPIPublicV1SystemRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLearnAPIPublicV1SystemRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetLearnAPIPublicV1SystemRolesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLearnAPIPublicV1SystemRolesOK creates a GetLearnAPIPublicV1SystemRolesOK with default headers values
func NewGetLearnAPIPublicV1SystemRolesOK() *GetLearnAPIPublicV1SystemRolesOK {
	return &GetLearnAPIPublicV1SystemRolesOK{}
}

/*GetLearnAPIPublicV1SystemRolesOK handles this case with default header values.

OK
*/
type GetLearnAPIPublicV1SystemRolesOK struct {
	Payload *GetLearnAPIPublicV1SystemRolesOKBody
}

func (o *GetLearnAPIPublicV1SystemRolesOK) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/systemRoles][%d] getLearnApiPublicV1SystemRolesOK  %+v", 200, o.Payload)
}

func (o *GetLearnAPIPublicV1SystemRolesOK) GetPayload() *GetLearnAPIPublicV1SystemRolesOKBody {
	return o.Payload
}

func (o *GetLearnAPIPublicV1SystemRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetLearnAPIPublicV1SystemRolesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV1SystemRolesForbidden creates a GetLearnAPIPublicV1SystemRolesForbidden with default headers values
func NewGetLearnAPIPublicV1SystemRolesForbidden() *GetLearnAPIPublicV1SystemRolesForbidden {
	return &GetLearnAPIPublicV1SystemRolesForbidden{}
}

/*GetLearnAPIPublicV1SystemRolesForbidden handles this case with default header values.

Access Denied
*/
type GetLearnAPIPublicV1SystemRolesForbidden struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV1SystemRolesForbidden) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/systemRoles][%d] getLearnApiPublicV1SystemRolesForbidden  %+v", 403, o.Payload)
}

func (o *GetLearnAPIPublicV1SystemRolesForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV1SystemRolesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetLearnAPIPublicV1SystemRolesOKBody get learn API public v1 system roles o k body
swagger:model GetLearnAPIPublicV1SystemRolesOKBody
*/
type GetLearnAPIPublicV1SystemRolesOKBody struct {

	// paging
	Paging *models.PagingInfo `json:"paging,omitempty"`

	// results
	// Required: true
	Results []*models.SystemRole `json:"results"`
}

// Validate validates this get learn API public v1 system roles o k body
func (o *GetLearnAPIPublicV1SystemRolesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePaging(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetLearnAPIPublicV1SystemRolesOKBody) validatePaging(formats strfmt.Registry) error {

	if swag.IsZero(o.Paging) { // not required
		return nil
	}

	if o.Paging != nil {
		if err := o.Paging.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getLearnApiPublicV1SystemRolesOK" + "." + "paging")
			}
			return err
		}
	}

	return nil
}

func (o *GetLearnAPIPublicV1SystemRolesOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("getLearnApiPublicV1SystemRolesOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getLearnApiPublicV1SystemRolesOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetLearnAPIPublicV1SystemRolesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetLearnAPIPublicV1SystemRolesOKBody) UnmarshalBinary(b []byte) error {
	var res GetLearnAPIPublicV1SystemRolesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
