// Code generated by go-swagger; DO NOT EDIT.

package course_grades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDReader is a Reader for the GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnID structure.
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK handles this case with default header values.

OK
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK struct {
	Payload *models.GradeColumnV2
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdOK  %+v", 200, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK) GetPayload() *models.GradeColumnV2 {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GradeColumnV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest handles this case with default header values.

Bad Request
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden handles this case with default header values.

Forbidden
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdForbidden  %+v", 403, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound handles this case with default header values.

Not Found
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdNotFound  %+v", 404, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
