// Code generated by go-swagger; DO NOT EDIT.

package course_grades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsReader is a Reader for the GetLearnAPIPublicV2CoursesCourseIDGradebookColumns structure.
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK handles this case with default header values.

OK
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK struct {
	Payload *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsOK  %+v", 200, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK) GetPayload() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest handles this case with default header values.

Bad Request
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsBadRequest  %+v", 400, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden handles this case with default header values.

Forbidden
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsForbidden  %+v", 403, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound creates a GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound with default headers values
func NewGetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound() *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound {
	return &GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound{}
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound handles this case with default header values.

Not Found
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v2/courses/{courseId}/gradebook/columns][%d] getLearnApiPublicV2CoursesCourseIdGradebookColumnsNotFound  %+v", 404, o.Payload)
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody get learn API public v2 courses course ID gradebook columns o k body
swagger:model GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody
*/
type GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody struct {

	// paging
	Paging *models.PagingInfo `json:"paging,omitempty"`

	// results
	// Required: true
	Results []*models.GradeColumnV2 `json:"results"`
}

// Validate validates this get learn API public v2 courses course ID gradebook columns o k body
func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePaging(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody) validatePaging(formats strfmt.Registry) error {

	if swag.IsZero(o.Paging) { // not required
		return nil
	}

	if o.Paging != nil {
		if err := o.Paging.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getLearnApiPublicV2CoursesCourseIdGradebookColumnsOK" + "." + "paging")
			}
			return err
		}
	}

	return nil
}

func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("getLearnApiPublicV2CoursesCourseIdGradebookColumnsOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getLearnApiPublicV2CoursesCourseIdGradebookColumnsOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody) UnmarshalBinary(b []byte) error {
	var res GetLearnAPIPublicV2CoursesCourseIDGradebookColumnsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
