// Code generated by go-swagger; DO NOT EDIT.

package course_grades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsReader is a Reader for the PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttempts structure.
type PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated creates a PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated with default headers values
func NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated() *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated {
	return &PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated{}
}

/*PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated handles this case with default header values.

Created
*/
type PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated struct {
	Payload *models.AttemptV2
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated) Error() string {
	return fmt.Sprintf("[POST /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}/attempts][%d] postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsCreated  %+v", 201, o.Payload)
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated) GetPayload() *models.AttemptV2 {
	return o.Payload
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AttemptV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest creates a PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest with default headers values
func NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest() *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest {
	return &PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest{}
}

/*PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest handles this case with default header values.

Bad Request
*/
type PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest struct {
	Payload *models.RestException
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest) Error() string {
	return fmt.Sprintf("[POST /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}/attempts][%d] postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBadRequest  %+v", 400, o.Payload)
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest) GetPayload() *models.RestException {
	return o.Payload
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden creates a PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden with default headers values
func NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden() *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden {
	return &PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden{}
}

/*PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden handles this case with default header values.

Forbidden
*/
type PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden struct {
	Payload *models.RestException
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden) Error() string {
	return fmt.Sprintf("[POST /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}/attempts][%d] postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsForbidden  %+v", 403, o.Payload)
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound creates a PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound with default headers values
func NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound() *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound {
	return &PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound{}
}

/*PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound handles this case with default header values.

Not Found
*/
type PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound struct {
	Payload *models.RestException
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound) Error() string {
	return fmt.Sprintf("[POST /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}/attempts][%d] postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsNotFound  %+v", 404, o.Payload)
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound) GetPayload() *models.RestException {
	return o.Payload
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict creates a PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict with default headers values
func NewPostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict() *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict {
	return &PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict{}
}

/*PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict handles this case with default header values.

Conflict
*/
type PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict struct {
	Payload *models.RestException
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict) Error() string {
	return fmt.Sprintf("[POST /learn/api/public/v2/courses/{courseId}/gradebook/columns/{columnId}/attempts][%d] postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsConflict  %+v", 409, o.Payload)
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict) GetPayload() *models.RestException {
	return o.Payload
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody post learn API public v2 courses course ID gradebook columns column ID attempts body
swagger:model PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody
*/
type PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody struct {

	// Return the attempt date associated with this attempt.
	// Format: date-time
	AttemptDate strfmt.DateTime `json:"attemptDate,omitempty"`

	// Whether the score associated with this attempt is ignored when computing the user's grade for the associated grade column.
	Exempt bool `json:"exempt,omitempty"`

	// The instructor feedback associated with this attempt.
	Feedback string `json:"feedback,omitempty"`

	// The instructor notes associated with this attempt.
	Notes string `json:"notes,omitempty"`

	// The reconciliation mode to use when reconciling the attempt grade.  When modifying reconciliationMode, score is also required.  A new score will not be calculated based on the reconciliationMode
	//
	// **Since**: 3700.2.0
	//
	//
	// | Type      | Description
	//  | --------- | --------- |
	// | Average |  |
	// | Highest |  |
	// | Lowest |  |
	// | Custom |  |
	//
	// Enum: [Average Highest Lowest Custom]
	ReconciliationMode string `json:"reconciliationMode,omitempty"`

	// The score associated with this attempt.
	Score float64 `json:"score,omitempty"`

	// The status of this attempt.
	//
	//
	// | Type      | Description
	//  | --------- | --------- |
	// | NotAttempted | none of the students in a group has submitted an attempt; applies only to group assessments |
	// | Abandoned |   **Deprecated**: Since 9.1 SP8 unsupported status, undetermined behavior if used. |
	// | InProgress | attempt activity has commenced, but has not been submitted for grading |
	// | Suspended |   **Deprecated**: Since 9.1 SP8 unsupported status, undetermined behavior if used. |
	// | Canceled |   **Deprecated**: Since 9.1 SP8 unsupported status, undetermined behavior if used. |
	// | NeedsGrading | attempt has been submitted for grading, but has not been fully graded |
	// | Completed | a grade has been entered for the attempt |
	// | InProgressAgain | attempt has been graded, but more student activity occurred after the grade was entered; applies only to collaborative tools such as discussions |
	// | NeedsGradingAgain | additional student activity occurring after a grade was entered requires that the attempt be regraded; applies only to collaborative tools such as discussions |
	//
	// Enum: [NotAttempted Abandoned InProgress Suspended Canceled NeedsGrading Completed InProgressAgain NeedsGradingAgain]
	Status string `json:"status,omitempty"`

	// The student comments associated with this attempt.
	StudentComments string `json:"studentComments,omitempty"`

	// The student submission text associated with this attempt.
	StudentSubmission string `json:"studentSubmission,omitempty"`

	// The text grade associated with this attempt.
	Text string `json:"text,omitempty"`

	// The user ID associated with this attempt.  Defaults to the authenticated user on create.  Can be specified as a user other than the authenticated user if the authenticated user has the "course.gradebook.MODIFY" entitlement and the authenticated application has the "course.attempt.nonowner.SUBMIT" entitlement.
	UserID string `json:"userId,omitempty"`
}

// Validate validates this post learn API public v2 courses course ID gradebook columns column ID attempts body
func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttemptDate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReconciliationMode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) validateAttemptDate(formats strfmt.Registry) error {

	if swag.IsZero(o.AttemptDate) { // not required
		return nil
	}

	if err := validate.FormatOf("attemptInput"+"."+"attemptDate", "body", "date-time", o.AttemptDate.String(), formats); err != nil {
		return err
	}

	return nil
}

var postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeReconciliationModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Average","Highest","Lowest","Custom"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeReconciliationModePropEnum = append(postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeReconciliationModePropEnum, v)
	}
}

const (

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeAverage captures enum value "Average"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeAverage string = "Average"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeHighest captures enum value "Highest"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeHighest string = "Highest"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeLowest captures enum value "Lowest"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeLowest string = "Lowest"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeCustom captures enum value "Custom"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyReconciliationModeCustom string = "Custom"
)

// prop value enum
func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) validateReconciliationModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeReconciliationModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) validateReconciliationMode(formats strfmt.Registry) error {

	if swag.IsZero(o.ReconciliationMode) { // not required
		return nil
	}

	// value enum
	if err := o.validateReconciliationModeEnum("attemptInput"+"."+"reconciliationMode", "body", o.ReconciliationMode); err != nil {
		return err
	}

	return nil
}

var postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NotAttempted","Abandoned","InProgress","Suspended","Canceled","NeedsGrading","Completed","InProgressAgain","NeedsGradingAgain"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeStatusPropEnum = append(postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeStatusPropEnum, v)
	}
}

const (

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusNotAttempted captures enum value "NotAttempted"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusNotAttempted string = "NotAttempted"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusAbandoned captures enum value "Abandoned"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusAbandoned string = "Abandoned"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusInProgress captures enum value "InProgress"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusInProgress string = "InProgress"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusSuspended captures enum value "Suspended"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusSuspended string = "Suspended"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusCanceled captures enum value "Canceled"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusCanceled string = "Canceled"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusNeedsGrading captures enum value "NeedsGrading"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusNeedsGrading string = "NeedsGrading"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusCompleted captures enum value "Completed"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusCompleted string = "Completed"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusInProgressAgain captures enum value "InProgressAgain"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusInProgressAgain string = "InProgressAgain"

	// PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusNeedsGradingAgain captures enum value "NeedsGradingAgain"
	PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBodyStatusNeedsGradingAgain string = "NeedsGradingAgain"
)

// prop value enum
func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postLearnApiPublicV2CoursesCourseIdGradebookColumnsColumnIdAttemptsBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("attemptInput"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody) UnmarshalBinary(b []byte) error {
	var res PostLearnAPIPublicV2CoursesCourseIDGradebookColumnsColumnIDAttemptsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
