// Code generated by go-swagger; DO NOT EDIT.

package deprecated_courses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostLearnAPIPublicV2CoursesParams creates a new PostLearnAPIPublicV2CoursesParams object
// with the default values initialized.
func NewPostLearnAPIPublicV2CoursesParams() *PostLearnAPIPublicV2CoursesParams {
	var ()
	return &PostLearnAPIPublicV2CoursesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLearnAPIPublicV2CoursesParamsWithTimeout creates a new PostLearnAPIPublicV2CoursesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLearnAPIPublicV2CoursesParamsWithTimeout(timeout time.Duration) *PostLearnAPIPublicV2CoursesParams {
	var ()
	return &PostLearnAPIPublicV2CoursesParams{

		timeout: timeout,
	}
}

// NewPostLearnAPIPublicV2CoursesParamsWithContext creates a new PostLearnAPIPublicV2CoursesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLearnAPIPublicV2CoursesParamsWithContext(ctx context.Context) *PostLearnAPIPublicV2CoursesParams {
	var ()
	return &PostLearnAPIPublicV2CoursesParams{

		Context: ctx,
	}
}

// NewPostLearnAPIPublicV2CoursesParamsWithHTTPClient creates a new PostLearnAPIPublicV2CoursesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLearnAPIPublicV2CoursesParamsWithHTTPClient(client *http.Client) *PostLearnAPIPublicV2CoursesParams {
	var ()
	return &PostLearnAPIPublicV2CoursesParams{
		HTTPClient: client,
	}
}

/*PostLearnAPIPublicV2CoursesParams contains all the parameters to send to the API endpoint
for the post learn API public v2 courses operation typically these are written to a http.Request
*/
type PostLearnAPIPublicV2CoursesParams struct {

	/*Fields
	  A comma-delimited list of fields to include in the response. If not specified, all fields will be returned.

	*/
	Fields *string
	/*Input
	  JSON input object.

	*/
	Input PostLearnAPIPublicV2CoursesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) WithTimeout(timeout time.Duration) *PostLearnAPIPublicV2CoursesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) WithContext(ctx context.Context) *PostLearnAPIPublicV2CoursesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) WithHTTPClient(client *http.Client) *PostLearnAPIPublicV2CoursesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) WithFields(fields *string) *PostLearnAPIPublicV2CoursesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithInput adds the input to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) WithInput(input PostLearnAPIPublicV2CoursesBody) *PostLearnAPIPublicV2CoursesParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post learn API public v2 courses params
func (o *PostLearnAPIPublicV2CoursesParams) SetInput(input PostLearnAPIPublicV2CoursesBody) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostLearnAPIPublicV2CoursesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if err := r.SetBodyParam(o.Input); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
