// Code generated by go-swagger; DO NOT EDIT.

package course_announcements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDReader is a Reader for the GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementID structure.
type GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK creates a GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK with default headers values
func NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK() *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK {
	return &GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK{}
}

/*GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK handles this case with default header values.

OK
*/
type GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK struct {
	Payload *models.CourseAnnouncement
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/courses/{courseId}/announcements/{announcementId}][%d] getLearnApiPublicV1CoursesCourseIdAnnouncementsAnnouncementIdOK  %+v", 200, o.Payload)
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK) GetPayload() *models.CourseAnnouncement {
	return o.Payload
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CourseAnnouncement)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden creates a GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden with default headers values
func NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden() *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden {
	return &GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden{}
}

/*GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden handles this case with default header values.

The currently authenticated user has insufficient privileges to update an announcement
*/
type GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/courses/{courseId}/announcements/{announcementId}][%d] getLearnApiPublicV1CoursesCourseIdAnnouncementsAnnouncementIdForbidden  %+v", 403, o.Payload)
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound creates a GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound with default headers values
func NewGetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound() *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound {
	return &GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound{}
}

/*GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound handles this case with default header values.

Announcement cannot be found
*/
type GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/courses/{courseId}/announcements/{announcementId}][%d] getLearnApiPublicV1CoursesCourseIdAnnouncementsAnnouncementIdNotFound  %+v", 404, o.Payload)
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV1CoursesCourseIDAnnouncementsAnnouncementIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
