// Code generated by go-swagger; DO NOT EDIT.

package performance_dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusReader is a Reader for the GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatus structure.
type GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK creates a GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK with default headers values
func NewGetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK() *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK {
	return &GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK{}
}

/*GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK handles this case with default header values.

OK
*/
type GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK struct {
	Payload *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/courses/{courseId}/performance/contentReviewStatus][%d] getLearnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusOK  %+v", 200, o.Payload)
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK) GetPayload() *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody {
	return o.Payload
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden creates a GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden with default headers values
func NewGetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden() *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden {
	return &GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden{}
}

/*GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden handles this case with default header values.

Forbidden
*/
type GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden struct {
	Payload *models.RestException
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden) Error() string {
	return fmt.Sprintf("[GET /learn/api/public/v1/courses/{courseId}/performance/contentReviewStatus][%d] getLearnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusForbidden  %+v", 403, o.Payload)
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody get learn API public v1 courses course ID performance content review status o k body
swagger:model GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody
*/
type GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody struct {

	// paging
	Paging *models.PagingInfo `json:"paging,omitempty"`

	// results
	// Required: true
	Results []*models.AggregateReviewStatus `json:"results"`
}

// Validate validates this get learn API public v1 courses course ID performance content review status o k body
func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePaging(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody) validatePaging(formats strfmt.Registry) error {

	if swag.IsZero(o.Paging) { // not required
		return nil
	}

	if o.Paging != nil {
		if err := o.Paging.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getLearnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusOK" + "." + "paging")
			}
			return err
		}
	}

	return nil
}

func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("getLearnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getLearnApiPublicV1CoursesCourseIdPerformanceContentReviewStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody) UnmarshalBinary(b []byte) error {
	var res GetLearnAPIPublicV1CoursesCourseIDPerformanceContentReviewStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
