// Code generated by go-swagger; DO NOT EDIT.

package course_assessments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams creates a new PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams object
// with the default values initialized.
func NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams() *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParamsWithTimeout creates a new PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParamsWithTimeout(timeout time.Duration) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams{

		timeout: timeout,
	}
}

// NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParamsWithContext creates a new PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParamsWithContext(ctx context.Context) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams{

		Context: ctx,
	}
}

// NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParamsWithHTTPClient creates a new PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParamsWithHTTPClient(client *http.Client) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	var ()
	return &PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams{
		HTTPClient: client,
	}
}

/*PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams contains all the parameters to send to the API endpoint
for the patch learn API public v1 courses course ID assessments assessment ID questions question ID operation typically these are written to a http.Request
*/
type PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams struct {

	/*AssessmentID*/
	AssessmentID string
	/*CourseID
	 The course or organization ID.  This may be the primary ID, or any of the secondary IDs prefixed with the ID type.

	| ID type    | Example                               |
	|------------|---------------------------------------|
	| primary    | _123_1                                |
	| externalId | externalId:math101                    |
	| courseId   | courseId:math101                      |
	| uuid       | uuid:915c7567d76d444abf1eed56aad3beb5 |


	*/
	CourseID string
	/*Fields
	  A comma-delimited list of fields to include in the response. If not specified, all fields will be returned.

	*/
	Fields *string
	/*Input
	  JSON input object.

	*/
	Input PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDBody
	/*QuestionID*/
	QuestionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithTimeout(timeout time.Duration) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithContext(ctx context.Context) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithHTTPClient(client *http.Client) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssessmentID adds the assessmentID to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithAssessmentID(assessmentID string) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetAssessmentID(assessmentID)
	return o
}

// SetAssessmentID adds the assessmentId to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetAssessmentID(assessmentID string) {
	o.AssessmentID = assessmentID
}

// WithCourseID adds the courseID to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithCourseID(courseID string) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetCourseID(courseID string) {
	o.CourseID = courseID
}

// WithFields adds the fields to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithFields(fields *string) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithInput adds the input to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithInput(input PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDBody) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetInput(input PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDBody) {
	o.Input = input
}

// WithQuestionID adds the questionID to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WithQuestionID(questionID string) *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams {
	o.SetQuestionID(questionID)
	return o
}

// SetQuestionID adds the questionId to the patch learn API public v1 courses course ID assessments assessment ID questions question ID params
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) SetQuestionID(questionID string) {
	o.QuestionID = questionID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchLearnAPIPublicV1CoursesCourseIDAssessmentsAssessmentIDQuestionsQuestionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assessmentId
	if err := r.SetPathParam("assessmentId", o.AssessmentID); err != nil {
		return err
	}

	// path param courseId
	if err := r.SetPathParam("courseId", o.CourseID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if err := r.SetBodyParam(o.Input); err != nil {
		return err
	}

	// path param questionId
	if err := r.SetPathParam("questionId", o.QuestionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
