// Code generated by go-swagger; DO NOT EDIT.

package course_grade_attempts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jakemakesstuff/blackboard-go/models"
)

// DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDReader is a Reader for the DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileID structure.
type DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent creates a DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent with default headers values
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent() *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent {
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent{}
}

/*DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent handles this case with default header values.

No Content
*/
type DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent struct {
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /learn/api/public/v1/courses/{courseId}/gradebook/attempts/{attemptId}/files/{attemptFileId}][%d] deleteLearnApiPublicV1CoursesCourseIdGradebookAttemptsAttemptIdFilesAttemptFileIdNoContent ", 204)
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest creates a DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest with default headers values
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest() *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest {
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest{}
}

/*DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest handles this case with default header values.

Bad Request
*/
type DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest struct {
	Payload *models.RestException
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /learn/api/public/v1/courses/{courseId}/gradebook/attempts/{attemptId}/files/{attemptFileId}][%d] deleteLearnApiPublicV1CoursesCourseIdGradebookAttemptsAttemptIdFilesAttemptFileIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest) GetPayload() *models.RestException {
	return o.Payload
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden creates a DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden with default headers values
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden() *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden {
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden{}
}

/*DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden handles this case with default header values.

Forbidden
*/
type DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden struct {
	Payload *models.RestException
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /learn/api/public/v1/courses/{courseId}/gradebook/attempts/{attemptId}/files/{attemptFileId}][%d] deleteLearnApiPublicV1CoursesCourseIdGradebookAttemptsAttemptIdFilesAttemptFileIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden) GetPayload() *models.RestException {
	return o.Payload
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound creates a DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound with default headers values
func NewDeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound() *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound {
	return &DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound{}
}

/*DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound handles this case with default header values.

Not Found
*/
type DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound struct {
	Payload *models.RestException
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /learn/api/public/v1/courses/{courseId}/gradebook/attempts/{attemptId}/files/{attemptFileId}][%d] deleteLearnApiPublicV1CoursesCourseIdGradebookAttemptsAttemptIdFilesAttemptFileIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound) GetPayload() *models.RestException {
	return o.Payload
}

func (o *DeleteLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestException)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
