// Code generated by go-swagger; DO NOT EDIT.

package course_grade_attempts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams object
// with the default values initialized.
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams() *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParamsWithTimeout creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParamsWithTimeout(timeout time.Duration) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams{

		timeout: timeout,
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParamsWithContext creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParamsWithContext(ctx context.Context) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams{

		Context: ctx,
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParamsWithHTTPClient creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParamsWithHTTPClient(client *http.Client) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams{
		HTTPClient: client,
	}
}

/*GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams contains all the parameters to send to the API endpoint
for the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download operation typically these are written to a http.Request
*/
type GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams struct {

	/*AttemptFileID*/
	AttemptFileID string
	/*AttemptID*/
	AttemptID string
	/*CourseID
	 The course or organization ID.  This may be the primary ID, or any of the secondary IDs prefixed with the ID type.

	| ID type    | Example                               |
	|------------|---------------------------------------|
	| primary    | _123_1                                |
	| externalId | externalId:math101                    |
	| courseId   | courseId:math101                      |
	| uuid       | uuid:915c7567d76d444abf1eed56aad3beb5 |


	*/
	CourseID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) WithTimeout(timeout time.Duration) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) WithContext(ctx context.Context) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) WithHTTPClient(client *http.Client) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttemptFileID adds the attemptFileID to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) WithAttemptFileID(attemptFileID string) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	o.SetAttemptFileID(attemptFileID)
	return o
}

// SetAttemptFileID adds the attemptFileId to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) SetAttemptFileID(attemptFileID string) {
	o.AttemptFileID = attemptFileID
}

// WithAttemptID adds the attemptID to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) WithAttemptID(attemptID string) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	o.SetAttemptID(attemptID)
	return o
}

// SetAttemptID adds the attemptId to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) SetAttemptID(attemptID string) {
	o.AttemptID = attemptID
}

// WithCourseID adds the courseID to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) WithCourseID(courseID string) *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the get learn API public v1 courses course ID gradebook attempts attempt ID files attempt file ID download params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) SetCourseID(courseID string) {
	o.CourseID = courseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesAttemptFileIDDownloadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param attemptFileId
	if err := r.SetPathParam("attemptFileId", o.AttemptFileID); err != nil {
		return err
	}

	// path param attemptId
	if err := r.SetPathParam("attemptId", o.AttemptID); err != nil {
		return err
	}

	// path param courseId
	if err := r.SetPathParam("courseId", o.CourseID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
