// Code generated by go-swagger; DO NOT EDIT.

package course_grade_attempts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams creates a new PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams object
// with the default values initialized.
func NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams() *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	var ()
	return &PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParamsWithTimeout creates a new PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParamsWithTimeout(timeout time.Duration) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	var ()
	return &PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams{

		timeout: timeout,
	}
}

// NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParamsWithContext creates a new PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParamsWithContext(ctx context.Context) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	var ()
	return &PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams{

		Context: ctx,
	}
}

// NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParamsWithHTTPClient creates a new PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParamsWithHTTPClient(client *http.Client) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	var ()
	return &PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams{
		HTTPClient: client,
	}
}

/*PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams contains all the parameters to send to the API endpoint
for the post learn API public v1 courses course ID gradebook attempts attempt ID files operation typically these are written to a http.Request
*/
type PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams struct {

	/*AttemptFileTOPubV1*/
	AttemptFileTOPubV1 PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesBody
	/*AttemptID*/
	AttemptID string
	/*CourseID
	 The course or organization ID.  This may be the primary ID, or any of the secondary IDs prefixed with the ID type.

	| ID type    | Example                               |
	|------------|---------------------------------------|
	| primary    | _123_1                                |
	| externalId | externalId:math101                    |
	| courseId   | courseId:math101                      |
	| uuid       | uuid:915c7567d76d444abf1eed56aad3beb5 |


	*/
	CourseID string
	/*Fields
	  A comma-delimited list of fields to include in the response. If not specified, all fields will be returned.

	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WithTimeout(timeout time.Duration) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WithContext(ctx context.Context) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WithHTTPClient(client *http.Client) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttemptFileTOPubV1 adds the attemptFileTOPubV1 to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WithAttemptFileTOPubV1(attemptFileTOPubV1 PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesBody) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	o.SetAttemptFileTOPubV1(attemptFileTOPubV1)
	return o
}

// SetAttemptFileTOPubV1 adds the attemptFileTOPubV1 to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) SetAttemptFileTOPubV1(attemptFileTOPubV1 PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesBody) {
	o.AttemptFileTOPubV1 = attemptFileTOPubV1
}

// WithAttemptID adds the attemptID to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WithAttemptID(attemptID string) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	o.SetAttemptID(attemptID)
	return o
}

// SetAttemptID adds the attemptId to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) SetAttemptID(attemptID string) {
	o.AttemptID = attemptID
}

// WithCourseID adds the courseID to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WithCourseID(courseID string) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) SetCourseID(courseID string) {
	o.CourseID = courseID
}

// WithFields adds the fields to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WithFields(fields *string) *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the post learn API public v1 courses course ID gradebook attempts attempt ID files params
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *PostLearnAPIPublicV1CoursesCourseIDGradebookAttemptsAttemptIDFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.AttemptFileTOPubV1); err != nil {
		return err
	}

	// path param attemptId
	if err := r.SetPathParam("attemptId", o.AttemptID); err != nil {
		return err
	}

	// path param courseId
	if err := r.SetPathParam("courseId", o.CourseID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
