// Code generated by go-swagger; DO NOT EDIT.

package course_categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams creates a new PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams object
// with the default values initialized.
func NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams() *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	var ()
	return &PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParamsWithTimeout creates a new PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParamsWithTimeout(timeout time.Duration) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	var ()
	return &PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams{

		timeout: timeout,
	}
}

// NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParamsWithContext creates a new PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParamsWithContext(ctx context.Context) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	var ()
	return &PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams{

		Context: ctx,
	}
}

// NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParamsWithHTTPClient creates a new PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParamsWithHTTPClient(client *http.Client) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	var ()
	return &PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams{
		HTTPClient: client,
	}
}

/*PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams contains all the parameters to send to the API endpoint
for the put learn API public v1 catalog categories category type category ID courses course ID operation typically these are written to a http.Request
*/
type PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams struct {

	/*CategoryID*/
	CategoryID string
	/*CategoryType*/
	CategoryType string
	/*CourseID
	 The course or organization ID.  This may be the primary ID, or any of the secondary IDs prefixed with the ID type.

	| ID type    | Example                               |
	|------------|---------------------------------------|
	| primary    | _123_1                                |
	| externalId | externalId:math101                    |
	| courseId   | courseId:math101                      |
	| uuid       | uuid:915c7567d76d444abf1eed56aad3beb5 |


	*/
	CourseID string
	/*Fields
	  A comma-delimited list of fields to include in the response. If not specified, all fields will be returned.

	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WithTimeout(timeout time.Duration) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WithContext(ctx context.Context) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WithHTTPClient(client *http.Client) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategoryID adds the categoryID to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WithCategoryID(categoryID string) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	o.SetCategoryID(categoryID)
	return o
}

// SetCategoryID adds the categoryId to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) SetCategoryID(categoryID string) {
	o.CategoryID = categoryID
}

// WithCategoryType adds the categoryType to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WithCategoryType(categoryType string) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	o.SetCategoryType(categoryType)
	return o
}

// SetCategoryType adds the categoryType to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) SetCategoryType(categoryType string) {
	o.CategoryType = categoryType
}

// WithCourseID adds the courseID to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WithCourseID(courseID string) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) SetCourseID(courseID string) {
	o.CourseID = courseID
}

// WithFields adds the fields to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WithFields(fields *string) *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the put learn API public v1 catalog categories category type category ID courses course ID params
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *PutLearnAPIPublicV1CatalogCategoriesCategoryTypeCategoryIDCoursesCourseIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param categoryId
	if err := r.SetPathParam("categoryId", o.CategoryID); err != nil {
		return err
	}

	// path param categoryType
	if err := r.SetPathParam("categoryType", o.CategoryType); err != nil {
		return err
	}

	// path param courseId
	if err := r.SetPathParam("courseId", o.CourseID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
