// Code generated by go-swagger; DO NOT EDIT.

package content_review

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new content review API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for content review API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus(params *GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusParams, authInfo runtime.ClientAuthInfoWriter) (*GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusOK, error)

	PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus(params *PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusParams, authInfo runtime.ClientAuthInfoWriter) (*PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus gets review status

  Obtain the review status for a content item. This endpoint will only fetch the reviewStatus if the corresponding content was previously marked as reviewable.

**Since**: 3700.16.0
*/
func (a *Client) GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus(params *GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusParams, authInfo runtime.ClientAuthInfoWriter) (*GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus",
		Method:             "GET",
		PathPattern:        "/learn/api/public/v1/courses/{courseId}/contents/{contentId}/users/{userId}/reviewStatus",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus updates review status

  Update the review status for a content item. This endpoint will only update the reviewStatus if the corresponding content was previously marked as reviewable.

**Since**: 3700.16.0
*/
func (a *Client) PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus(params *PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusParams, authInfo runtime.ClientAuthInfoWriter) (*PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus",
		Method:             "PATCH",
		PathPattern:        "/learn/api/public/v1/courses/{courseId}/contents/{contentId}/users/{userId}/reviewStatus",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PatchLearnAPIPublicV1CoursesCourseIDContentsContentIDUsersUserIDReviewStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
