// Code generated by go-swagger; DO NOT EDIT.

package calendar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams creates a new GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams object
// with the default values initialized.
func NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams() *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	var ()
	return &GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParamsWithTimeout creates a new GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParamsWithTimeout(timeout time.Duration) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	var ()
	return &GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams{

		timeout: timeout,
	}
}

// NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParamsWithContext creates a new GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParamsWithContext(ctx context.Context) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	var ()
	return &GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams{

		Context: ctx,
	}
}

// NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParamsWithHTTPClient creates a new GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParamsWithHTTPClient(client *http.Client) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	var ()
	return &GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams{
		HTTPClient: client,
	}
}

/*GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams contains all the parameters to send to the API endpoint
for the get learn API public v1 calendars items calendar item type calendar item ID operation typically these are written to a http.Request
*/
type GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams struct {

	/*CalendarItemID*/
	CalendarItemID string
	/*CalendarItemType*/
	CalendarItemType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) WithTimeout(timeout time.Duration) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) WithContext(ctx context.Context) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) WithHTTPClient(client *http.Client) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCalendarItemID adds the calendarItemID to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) WithCalendarItemID(calendarItemID string) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	o.SetCalendarItemID(calendarItemID)
	return o
}

// SetCalendarItemID adds the calendarItemId to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) SetCalendarItemID(calendarItemID string) {
	o.CalendarItemID = calendarItemID
}

// WithCalendarItemType adds the calendarItemType to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) WithCalendarItemType(calendarItemType string) *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams {
	o.SetCalendarItemType(calendarItemType)
	return o
}

// SetCalendarItemType adds the calendarItemType to the get learn API public v1 calendars items calendar item type calendar item ID params
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) SetCalendarItemType(calendarItemType string) {
	o.CalendarItemType = calendarItemType
}

// WriteToRequest writes these params to a swagger request
func (o *GetLearnAPIPublicV1CalendarsItemsCalendarItemTypeCalendarItemIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param calendarItemId
	if err := r.SetPathParam("calendarItemId", o.CalendarItemID); err != nil {
		return err
	}

	// path param calendarItemType
	if err := r.SetPathParam("calendarItemType", o.CalendarItemType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
