// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AttendanceDataDownloadURL attendance data download Url
//
// swagger:model AttendanceDataDownloadUrl
type AttendanceDataDownloadURL struct {

	// The download url of attendance data file.
	// Required: true
	DownloadURL *string `json:"downloadUrl"`
}

// Validate validates this attendance data download Url
func (m *AttendanceDataDownloadURL) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDownloadURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AttendanceDataDownloadURL) validateDownloadURL(formats strfmt.Registry) error {

	if err := validate.Required("downloadUrl", "body", m.DownloadURL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AttendanceDataDownloadURL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AttendanceDataDownloadURL) UnmarshalBinary(b []byte) error {
	var res AttendanceDataDownloadURL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
