// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Attempt attempt
//
// swagger:model Attempt
type Attempt struct {

	// The date on which this attempt was created.
	// Required: true
	// Read Only: true
	// Format: date-time
	Created strfmt.DateTime `json:"created"`

	// Whether the score associated with this attempt is ignored when computing the user's grade for the associated grade column.
	Exempt bool `json:"exempt,omitempty"`

	// The instructor feedback associated with this attempt.
	Feedback string `json:"feedback,omitempty"`

	// The group attempt ID associated with this student attempt.
	// Required: true
	// Read Only: true
	GroupAttemptID string `json:"groupAttemptId"`

	// Whether the score associated with this student attempt was overridden from the associated group attempt score. A value is only returned if the attempt grade is currently overridden.
	// Required: true
	// Read Only: true
	GroupOverride bool `json:"groupOverride"`

	// The primary ID for this attempt.
	// Required: true
	// Read Only: true
	ID string `json:"id"`

	// The instructor notes associated with this attempt.
	Notes string `json:"notes,omitempty"`

	// The score associated with this attempt.
	Score float64 `json:"score,omitempty"`

	// The status of this attempt.
	//
	//
	// | Type      | Description
	//  | --------- | --------- |
	// | NotAttempted | none of the students in a group has submitted an attempt; applies only to group assessments |
	// | Abandoned |   **Deprecated**: Since 9.1 SP8 unsupported status, undetermined behavior if used. |
	// | InProgress | attempt activity has commenced, but has not been submitted for grading |
	// | Suspended |   **Deprecated**: Since 9.1 SP8 unsupported status, undetermined behavior if used. |
	// | Canceled |   **Deprecated**: Since 9.1 SP8 unsupported status, undetermined behavior if used. |
	// | NeedsGrading | attempt has been submitted for grading, but has not been fully graded |
	// | Completed | a grade has been entered for the attempt |
	// | InProgressAgain | attempt has been graded, but more student activity occurred after the grade was entered; applies only to collaborative tools such as discussions |
	// | NeedsGradingAgain | additional student activity occurring after a grade was entered requires that the attempt be regraded; applies only to collaborative tools such as discussions |
	//
	// Enum: [NotAttempted Abandoned InProgress Suspended Canceled NeedsGrading Completed InProgressAgain NeedsGradingAgain]
	Status string `json:"status,omitempty"`

	// The student comments associated with this attempt.
	StudentComments string `json:"studentComments,omitempty"`

	// The student submission text associated with this attempt.
	StudentSubmission string `json:"studentSubmission,omitempty"`

	// The text representation of grade for this attempt.
	Text string `json:"text,omitempty"`

	// The user ID associated with this attempt.
	// Required: true
	// Read Only: true
	UserID string `json:"userId"`
}

// Validate validates this attempt
func (m *Attempt) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupAttemptID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupOverride(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Attempt) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", strfmt.DateTime(m.Created)); err != nil {
		return err
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Attempt) validateGroupAttemptID(formats strfmt.Registry) error {

	if err := validate.RequiredString("groupAttemptId", "body", string(m.GroupAttemptID)); err != nil {
		return err
	}

	return nil
}

func (m *Attempt) validateGroupOverride(formats strfmt.Registry) error {

	if err := validate.Required("groupOverride", "body", bool(m.GroupOverride)); err != nil {
		return err
	}

	return nil
}

func (m *Attempt) validateID(formats strfmt.Registry) error {

	if err := validate.RequiredString("id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

var attemptTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NotAttempted","Abandoned","InProgress","Suspended","Canceled","NeedsGrading","Completed","InProgressAgain","NeedsGradingAgain"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		attemptTypeStatusPropEnum = append(attemptTypeStatusPropEnum, v)
	}
}

const (

	// AttemptStatusNotAttempted captures enum value "NotAttempted"
	AttemptStatusNotAttempted string = "NotAttempted"

	// AttemptStatusAbandoned captures enum value "Abandoned"
	AttemptStatusAbandoned string = "Abandoned"

	// AttemptStatusInProgress captures enum value "InProgress"
	AttemptStatusInProgress string = "InProgress"

	// AttemptStatusSuspended captures enum value "Suspended"
	AttemptStatusSuspended string = "Suspended"

	// AttemptStatusCanceled captures enum value "Canceled"
	AttemptStatusCanceled string = "Canceled"

	// AttemptStatusNeedsGrading captures enum value "NeedsGrading"
	AttemptStatusNeedsGrading string = "NeedsGrading"

	// AttemptStatusCompleted captures enum value "Completed"
	AttemptStatusCompleted string = "Completed"

	// AttemptStatusInProgressAgain captures enum value "InProgressAgain"
	AttemptStatusInProgressAgain string = "InProgressAgain"

	// AttemptStatusNeedsGradingAgain captures enum value "NeedsGradingAgain"
	AttemptStatusNeedsGradingAgain string = "NeedsGradingAgain"
)

// prop value enum
func (m *Attempt) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, attemptTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Attempt) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *Attempt) validateUserID(formats strfmt.Registry) error {

	if err := validate.RequiredString("userId", "body", string(m.UserID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Attempt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Attempt) UnmarshalBinary(b []byte) error {
	var res Attempt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
