// Code generated by go-swagger; DO NOT EDIT.

package course_gradebook_categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams object
// with the default values initialized.
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams() *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParamsWithTimeout creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParamsWithTimeout(timeout time.Duration) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams{

		timeout: timeout,
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParamsWithContext creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParamsWithContext(ctx context.Context) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams{

		Context: ctx,
	}
}

// NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParamsWithHTTPClient creates a new GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParamsWithHTTPClient(client *http.Client) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	var ()
	return &GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams{
		HTTPClient: client,
	}
}

/*GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams contains all the parameters to send to the API endpoint
for the get learn API public v1 courses course ID gradebook categories category ID operation typically these are written to a http.Request
*/
type GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams struct {

	/*CategoryID
	  the ID of the category to return

	*/
	CategoryID string
	/*CourseID
	 The course or organization ID.  This may be the primary ID, or any of the secondary IDs prefixed with the ID type.

	| ID type    | Example                               |
	|------------|---------------------------------------|
	| primary    | _123_1                                |
	| externalId | externalId:math101                    |
	| courseId   | courseId:math101                      |
	| uuid       | uuid:915c7567d76d444abf1eed56aad3beb5 |


	*/
	CourseID string
	/*Fields
	  A comma-delimited list of fields to include in the response. If not specified, all fields will be returned.

	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) WithTimeout(timeout time.Duration) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) WithContext(ctx context.Context) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) WithHTTPClient(client *http.Client) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategoryID adds the categoryID to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) WithCategoryID(categoryID string) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	o.SetCategoryID(categoryID)
	return o
}

// SetCategoryID adds the categoryId to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) SetCategoryID(categoryID string) {
	o.CategoryID = categoryID
}

// WithCourseID adds the courseID to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) WithCourseID(courseID string) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	o.SetCourseID(courseID)
	return o
}

// SetCourseID adds the courseId to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) SetCourseID(courseID string) {
	o.CourseID = courseID
}

// WithFields adds the fields to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) WithFields(fields *string) *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get learn API public v1 courses course ID gradebook categories category ID params
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *GetLearnAPIPublicV1CoursesCourseIDGradebookCategoriesCategoryIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param categoryId
	if err := r.SetPathParam("categoryId", o.CategoryID); err != nil {
		return err
	}

	// path param courseId
	if err := r.SetPathParam("courseId", o.CourseID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
